# .air.toml
# Config file for [Air](https://github.com/air-verse/air) in TOML format

root = "."
tmp_dir = "tmp"

[build]
# Just plain old shell command. You could use `make` as well.
cmd = "go build -o ./tmp/main ."
# Binary file produced by `cmd`.
bin = "tmp/main"
# Custom binary.
full_bin = "./tmp/main"
# Watch these filename patterns.
include_ext = ["go", "tpl", "tmpl", "html"]
# Ignore these filename patterns or directories.
# exclude_dir = ["assets", "tmp", "vendor"]
# It's not necessary to trigger build each time file changes if it's too frequent.
delay = 1000 # ms
# Stop running old binary when build errors occur.
stop_on_error = true
# Send Interrupt on Windows before "air -w" exits
# (don't set it to false if you need to see the error details)
send_interrupt = false
# Delay after sending Interrupt
kill_delay = 500 # ms

[log]
# Show log time
time = true

[color]
# Customize each part's color. If no color found, use the raw app log.
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
# Delete tmp directory on exit
clean_on_exit = true
